version: "3"

services:

  api:
    build: .
    container_name: darkpattern-api
    ports:
      - "8000:8000"

  streamlit:
    build: .
    container_name: darkpattern-dashboard
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"

  n8n:
    image: n8nio/n8n
    container_name: darkpattern-n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n